nxp/imxrt10xx/ccm: fix clang error
error: ISO C++ only allows ':' in member enumeration declaration to
introduce a fixed underlying type, not an anonymous bit-field